---
title: "data reshaping 2"
author: "De Farmer"
date: "4/30/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Data frame**

```{r}
df <- data.frame(distance=c(500,353,167,120,553,340,223,880),time=c(5.5,6,4,2,6.3,3,4.5,9),stringsAsFactors = TRUE)
df

```

Adding column to data frame

speed=distance/time


```{r}
df$speed <- df$distance/df$time
df
```

Add let speed >=70 be fast

```{r}
df$fast_slow <- ifelse(df$speed>=70,"Fast","Slow")
df
class(df$fast_slow)
```


more columns

```{r}
df$gender <- c("male","female","male","male","male","female","female","male")
df
```

Working on data

i.e data transformation

```{r}
df$gender <- ifelse(df$gender=="male",0,1)
df
```
Data transformation
```{r}
df <- transform(df,gender=as.factor(gender))
df
```

**Analysing Factor Data**

```{r}
table(df$gender,dnn = ("Gender"))

```

regression

```{r}
model <- lm(time~distance+gender,df)

model
summary(model)
```


Reducing decimal places

1:**Round**

```{r}
df$speed=round(df$speed,digits = 2)
df
```


